feature:
- head-branch: 'feature/*'
fix:
- head-branch: 'fix/*'
chore:
- head-branch: 'chore/*'
dependencies:
- any:
  - head-branch: 'dependencies/*'
  - head-branch: 'dependabot/*'
github-actions:
- any:
  - changed-files:
    - '.github/**'